### ISSUE TITLE
error in pycocotools

### ISSUE THREAD

**Issue by zhaoxin111** [Media-Smart/volkscv#2]
Thank you for sharing such a great job！However, I encountered a little problem in the process of tasting. Here is my simple code. The error seems to be related to cocoapi. How can I fix this?

anno_data = parse_data(
        format='coco',
        anno_path=r'coco/instances_train.json',
        ignore=True,
        min_size=1,
    )
danno = statistic_data(anno_data)

def data_statistics_defult():
    # default statistics
    danno.default_plot()  # statistics and plot
    danno.show()  # show the plot figure
    danno.export('./default', save_mode='folder')  # export the analysis results to a folder
    danno.clear()  # clean the plot figure in workspace

if __name__ == "__main__":
    data_statistics_defult()

Traceback (most recent call last):
  File "/home/zhaoxin/workspace/volkscv/usage.py", line 5, in <module>
    from volkscv.analyzer.statistics import statistic_data, statistic_anchor, statistic_fp
  File "/home/zhaoxin/workspace/volkscv/volkscv/__init__.py", line 1, in <module>
    from . import metrics, analyzer, utils
  File "/home/zhaoxin/workspace/volkscv/volkscv/metrics/__init__.py", line 1, in <module>
    from . import classification, detection, segmentation
  File "/home/zhaoxin/workspace/volkscv/volkscv/metrics/detection/__init__.py", line 1, in <module>
    from .base import BaseMetric, COCOAnalysis
  File "/home/zhaoxin/workspace/volkscv/volkscv/metrics/detection/base.py", line 6, in <module>
    from ...utils.cocoapi.pycocotools.coco import COCO
  File "/home/zhaoxin/workspace/volkscv/volkscv/utils/cocoapi/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/zhaoxin/workspace/volkscv/volkscv/utils/cocoapi/pycocotools/mask.py", line 3, in <module>
    from . import _mask
ImportError: cannot import name '_mask' from 'volkscv.utils.cocoapi.pycocotools'

**Comment by hxcai** [comment]
@zhaoxin111 Hi, please check volkscv has been successfully installed, and the _mask.c file exists in volkscv/utils/cocoapi/pycocotools.

**Comment by zhaoxin111** [comment]
> @zhaoxin111 Hi, please check volkscv has been successfully installed, and the _mask.c file exists in volkscv/utils/cocoapi/pycocotools.
volkscv was successfully installed and the _mask.c file exists.

**Comment by hxcai** [comment]
@zhaoxin111 try to use volkscv in other path, means not in the source code dir.

**Comment by zhaoxin111** [comment]
@hxcai 
the same error.
ImportError: cannot import name '_mask' from 'volkscv.utils.cocoapi.pycocotools'

**Comment by hxcai** [comment]
@zhaoxin111 could u please join the weixin group for communication
![image](https://user-images.githubusercontent.com/13350482/100103653-22e4d800-2ea0-11eb-8ce8-49f89491647c.png)
